[build]
  command = "yarn build"
  functions = "functions"
  publish = "build"

[dev]
  targetPort = 3000
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "build" # The path to your static content folder
  autoLaunch = true
