[build]
  command = "yarn run build"
  functions = "functions"
  publish = "dist"

[dev]
  targetPort = 3000
  port = 8888 # The port that the netlify dev will be accessible on
  publish = "dist" # The path to your static content folder
  autoLaunch = true
